<?php

  $tipo_listado = 0;
  $comision = 20801;
  $header = array();
  $un_header = array ( "sede" => 2, "d_sede" => "CIUDAD UNIVERSITARIA", "materia" => 8, "d_materia" => "BIOLOGIA", "horario" => 621, "d_horario" => "LU JU 7-10", "aula" => 113 );
  array_push($header, $un_header);
  $alumnos = array();
  $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);
    $un_alumno = array("apellido" => "CORIA", "nombre" => "CARLOS DAVID", "dni" => 40747968 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ESPINOLA MALUENDEZ", "nombre" => "JOSEFINA GRACIELA", "dni" => 35321517 ) ;
  array_push($alumnos, $un_alumno);  
  $un_alumno = array( "apellido" => "LOAIZA CARDENAS", "nombre" => "GERMAN OSWALDO", "dni" => 95767698 );
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "TRAVAGLINI", "nombre" => "ORNELLA", "dni" => 42591970 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "VIERA LOPEZ", "nombre" => "DANIEL ISAIAS", "dni" => 41222620 ) ;
  array_push($alumnos, $un_alumno);
  $un_alumno = array( "apellido" => "ZANNINI", "nombre" => "GIULIANA FIORELLA", "dni" => 39714632 ) ;
  array_push($alumnos, $un_alumno);

?>